// src/pages/api/contact.js

import sgMail from '@sendgrid/mail';

sgMail.setApiKey(process.env.SENDGRID_API_KEY);

export default async function handler(req, res) {
  if (req.method === 'POST') {
    const { name, email, message } = req.body;

    const msg = {
      to: 'sibomanabertrand47@gmail.com', 
      from: 'prochatapp@sgeneratorapp.online', 
      subject: `New contact form submission from ${name}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 10px; background-color: #ffffff;">
          <h2 style="background-color: #4CAF50; color: #ffffff; padding: 10px; border-radius: 5px 5px 0 0; text-align: center;">New Contact Form Submission</h2>
          <div style="padding: 20px;">
            <p style="font-size: 16px; line-height: 1.5;">
              <strong>Name:</strong> ${name}
            </p>
            <p style="font-size: 16px; line-height: 1.5;">
              <strong>Email:</strong> ${email}
            </p>
            <p style="font-size: 16px; line-height: 1.5;">
              <strong>Message:</strong>
            </p>
            <p style="font-size: 16px; line-height: 1.5;">
              ${message}
            </p>
          </div>
          <div style="background-color: #f0f0f0; padding: 10px; border-radius: 0 0 5px 5px; text-align: center;">
            <p style="font-size: 14px; color: #888888;">This email was generated by Veily's contact form.</p>
          </div>
        </div>
      `,
    };

    try {
      const response = await sgMail.send(msg);
      console.log('Email sent successfully:', response);
      res.status(200).json({ message: 'Email sent successfully' });
    } catch (error) {
      console.error('Error sending email:', error);
      res.status(500).json({ message: `Error: ${error.message}` });
    }
  } else {
    res.status(405).json({ message: 'Method not allowed' });
  }
}
